//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGebeya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dislike_for_rent_item
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int rent_id { get; set; }
        public string Dislike { get; set; }
    
        public virtual Rent Rent { get; set; }
        public virtual User User { get; set; }
    }
}
