//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGebeya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House_for_rent:Rent
    {
        public int house_id { get; set; }
        public string location { get; set; }
        public int number_of_bedrooms { get; set; }
        public int number_of_bathrooms { get; set; }
        public string house_name { get; set; }
        public string house_description { get; set; }
        public int price { get; set; }
        public bool availability { get; set; }
        public int payment_type_id { get; set; }
        public Nullable<int> house_type_id { get; set; }
        public int user_id { get; set; }
        public int rent_id { get; set; }
        public string house_image_path { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    
        public virtual House_type House_type { get; set; }
        public virtual payment_type payment_type { get; set; }
        public virtual Rent Rent { get; set; }
        public virtual User User { get; set; }
    }
}
