//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace MyGebeya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items_for_sale:sale
    {
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public bool availability { get; set; }
        public int price_per_item { get; set; }
        public int item_type_id { get; set; }
        public int user_id { get; set; }
        public int sales_id { get; set; }
        public string item_image_path { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public List<Item_type> item_Types { get; set; }

    
        public virtual Item_type Item_type { get; set; }
        public virtual sale sale { get; set; }
        public virtual User User { get; set; }
    }
}
