//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGebeya.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyGebeyaEntities : DbContext
    {
        public MyGebeyaEntities()
            : base("name=MyGebeyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Car_for_rent> Car_for_rent { get; set; }
        public virtual DbSet<Car_type> Car_type { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Comment_for_rent> Comment_for_rent { get; set; }
        public virtual DbSet<Dislike_for_rent_item> Dislike_for_rent_item { get; set; }
        public virtual DbSet<Dislikes_for_sale_item> Dislikes_for_sale_item { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<House_for_rent> House_for_rent { get; set; }
        public virtual DbSet<House_type> House_type { get; set; }
        public virtual DbSet<Item_type> Item_type { get; set; }
        public virtual DbSet<Items_for_rent> Items_for_rent { get; set; }
        public virtual DbSet<Items_for_sale> Items_for_sale { get; set; }
        public virtual DbSet<Likes_for_rent_item> Likes_for_rent_item { get; set; }
        public virtual DbSet<Likes_for_sale_item> Likes_for_sale_item { get; set; }
        public virtual DbSet<payment_type> payment_type { get; set; }
        public virtual DbSet<Rent> Rents { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
